### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by caneta** [neoclide/coc-css#10]
I've tried with `CocInstall coc-css` but I get the following:
```
[coc.nvim] Error on install coc-css: Error: write EPROTO 140370308294464:error:1408F10B:SSL routines:ssl3_get_record:wrong version num
ber:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
```
Any hints? Thank you.

**Comment by chemzqm** [comment]
Looks like your have wrong `$HTTP_PROXY`

**Comment by caneta** [comment]
Hi @chemzqm! I'm on Ubuntu Linux 16.04, running neovim 0.5.0-dev. and I have a correct conf of my proxy:
```
user@laptop:~$ env | grep $HTTP_PROXY
http_proxy=http://myproxy.it:1234/
https_proxy=https://myproxy.it:1234/
HTTPS_PROXY=https://myproxy.it:1234/
HTTP_PROXY=http://myproxy.it:1234/
```

**Comment by chemzqm** [comment]
You need make sure your HTTPS_PROXY works as expected.

**Comment by caneta** [comment]
It does, otherwise I would not able to write these messages on github...I had no proxy issues in installing coc.nvim: why should I have them installing its plugins?

**Comment by chemzqm** [comment]
It uses your `HTTP_PROXY` env for sending request.
Use `let $NO_PROXY = '*'` in your vimrc to avoid proxy.

**Comment by caneta** [comment]
`[coc.nvim] Installed extension: coc-css`
Thank you @chemzqm, that worked!
