### ISSUE TITLE
[Question] sass support

### ISSUE THREAD

**Issue by mnabila** [neoclide/coc-css#11]
how to use this extensions on sass file type ?

__--sorry if my english to bad__

**Comment by chemzqm** [comment]
Should just works.

**Comment by mnabila** [comment]
the completion only show from coc-emmet and coc-snippets not from LSP
and from vscode-css-language service say sass support was rejected [#33](https://github.com/microsoft/vscode-css-languageservice/issues/33) [#158]( https://github.com/microsoft/vscode-css-languageservice/issues/158#issue-451118937)

![Screenshot_20191118_041947](https://user-images.githubusercontent.com/37516576/69014293-518dc000-09bb-11ea-82f2-8f70c6e56d42.png)

**Comment by chemzqm** [comment]
It support scss only, checkout `:h g:coc_filetype_map`

**Comment by mnabila** [comment]
@chemzqm thanks for information
