### ISSUE TITLE
How to get SCSS Classname completion inside javascript.jsx filetype

### ISSUE THREAD

**Issue by rakshans1** [neoclide/coc-css#12]
![image](https://user-images.githubusercontent.com/12949352/72635647-4a673c00-3983-11ea-82ca-c28e895f0ec7.png)

**Comment by chemzqm** [comment]
Add `-` to your iskeyword option of javascript.jsx filetype.

**Comment by mosheavni** [comment]
> Add `-` to your iskeyword option of javascript.jsx filetype.

hey @chemzqm, it's not working for me.
I ran:
```
:setf javascript.jsx
:set iskeyword+=-
```
And I still don't have completions of CSS inside javascript

**Comment by chemzqm** [comment]
There's something wrong with the filter.

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.
