### ISSUE TITLE
coc-css Installed by vim-plug not working correctly!

### ISSUE THREAD

**Issue by awesomepandata** [neoclide/coc-css#13]
## versions

vim version: NVIM v0.5.0-397-g96059d72e
node version: v12.13.1
coc.nvim version: 0.0.75-0b7b4043c8
term: undefined
platform: win32

## Messages
...

When installing with a plugin manager, the completion not working, but when install with CocInstall, working normally 💃 

Installed via a plugin manager (vim-plug for example) is oficial supported?

**Comment by chemzqm** [comment]
You have to run `yarn install` in project folder.
