### ISSUE TITLE
SASS Modules support?

### ISSUE THREAD

**Issue by chris-burgin** [neoclide/coc-css#14]
The plugin is working great for almost everything, but does not seem to support new SASS Modules. Is there anything specific I need to do to enable support?

https://sass-lang.com/documentation/modules

**Comment by happy96026** [comment]
This plugin is using an outdated version of vscode-css-languageservice module. The module should be upgraded from 4.0.2 to the current one (4.2.0 at the time of writing) in order to support the new SASS module system.

**Comment by tomaskallup** [comment]
For those who stumble uppon this:
A workaround is to clone the repo, update vscode dependency, rebuild the package (there is a type error, which can be bypassed by `as any`) and copy `lib` content to `.config/coc/extensions/node_modules/coc-css/lib`.

I'll probably try to update it and create PR with proper types, but this is a quick hacky workaround

Edit: seems like there already is #19

**Comment by chemzqm** [comment]
It's fixed.
