### ISSUE TITLE
Support for template literals in js files

### ISSUE THREAD

**Issue by TxHawks** [neoclide/coc-css#15]
Many css-in-js libraries support writing css inside template strings. For instance, in Emotion you can do:

```js
import { css, } from 'emotion';

const style = css`
  margin-bottom: 2rem;
  color:  red;
`
```

It would be great if there was a way to enable coc-css when editing these template literals

**Comment by chemzqm** [comment]
It could be achieved by extension of tsserver, not this extension.

**Comment by TxHawks** [comment]
> It could be achieved by extension of tsserver, not this extension.

Is this something that's already actually possible with coc-tsserver, or should I open an issue there?

**Comment by chemzqm** [comment]
It's tsserver's extension, you should checkout if there is such kind of extension for tsserver.
