### ISSUE TITLE
Property css.filetypes is not allowed

### ISSUE THREAD

**Issue by jalberto** [neoclide/coc-css#16]
The readme mentions the setting `css.filetypes` but when I use it in `coc-settings.json` like `"css.filetypes": ["css", "sass", "scss"]` the settings linter says it is not allowed.

**Comment by chemzqm** [comment]
Yes, it's not supported any more.

**Comment by mosheavni** [comment]
> Yes, it's not supported any more.

So how can I have completion on JavaScript files?

**Comment by chemzqm** [comment]
> > Yes, it's not supported any more.
> 
> So how can I have completion on JavaScript files?

No, you should not use it for javascript files.
