### ISSUE TITLE
[Question] how to get suggestions appearing more conveniently

### ISSUE THREAD

**Issue by AnthonyPoschen** [neoclide/coc-css#2]
hi, i am not a vim wizard and i am struggling to workout how to make the suggestionbox appear when i manually type out element's, i would also love a way to put things like auto,inherit etc at the top above the 0 values. 
![gif css](https://user-images.githubusercontent.com/2253299/53789852-94b51980-3f79-11e9-87e0-657ebdf392db.gif)

**Comment by chemzqm** [comment]
> make the suggestionbox appear when i manually type out element's.

Trigger completion by `:` is not supported by css language server, hope VSCode could improve that.

>  i would also love a way to put things like auto,inherit etc at the top above the 0 values.

The css language server could improve it's sort logic or use AI's help , but the data from Miscrosoft only allowed for use with VSCode, not open source.

**Comment by AnthonyPoschen** [comment]
css language server has improved, no longer an issue.
