### ISSUE TITLE
Question. Enable css lsp on html files

### ISSUE THREAD

**Issue by Cvar1984** [neoclide/coc-css#20]
Hi is there any configuration to enable css lsp on html files? Thanks

**Comment by chemzqm** [comment]
No, use coc-html instead

**Comment by Cvar1984** [comment]
> No, use coc-html instead

its work fine, but does't work for twig files. I have installed coc-phpls, coc-html, coc-css

**Comment by chemzqm** [comment]
`:h g:coc_filetype_map`

**Comment by Cvar1984** [comment]
> `:h g:coc_filetype_map`

Thanks, it worked like a magic
