### ISSUE TITLE
Bad response from 401

### ISSUE THREAD

**Issue by gfsd3v** [neoclide/coc-css#23]
I've been trying to install for the last 30 minutes, dont know if is a problem with NPM but I'm getting 401 Unauthorized on running the install script.

**Comment by chemzqm** [comment]
Check register url in your .npmrc

**Comment by gfsd3v** [comment]
> Check register url in your .npmrc

wow, I was working on a new project and didnt see that there was a .npmrc in the root directory with a custom register URL, how dumb of me(sorry).

Closing this, thank you for your time.
