### ISSUE TITLE
Not adding semicolon after auto complete

### ISSUE THREAD

**Issue by jesperp** [neoclide/coc-css#24]
I can't get any semicolon after auto completing css properties. Trying both `<Enter> `and `<Tab>` after selecting completion suggestion. I have tried both an empty coc-config and one where I explicitly defined `css.completion.completePropertyWithSemicolon` with same non working result.

```
vim version: NVIM v0.4.4
node version: v12.18.1
coc.nvim version: 0.0.79-b1288b0de4
coc.nvim directory: /Users/jesper/.vim/plugged/coc.nvim
term: iTerm.app
platform: darwin
```

![coc-css-bug](https://user-images.githubusercontent.com/376921/96009410-ea81c100-0e40-11eb-835d-546974ff96e6.gif)

Any ideas? And how would I even begin to debug something like this?

**Comment by jesperp** [comment]
FWIW, I also tried disabling all my plugins except coc.nvim and still not working

**Comment by chemzqm** [comment]
No such feature

**Comment by jesperp** [comment]
What is `completePropertyWithSemicolon` doing then?

**Comment by chemzqm** [comment]
Could be issue with `vscode-css-languageservice`, doesn't work on VSCode as well.
