### ISSUE TITLE
issue with floating auto complete window

### ISSUE THREAD

**Issue by amirhosseinadev** [neoclide/coc-css#25]
Hi,
I am a noobie with vim, when i use auto complete for css, floating window it's look like this,
is there a way i make it prettier?
![Screenshot (19)](https://user-images.githubusercontent.com/44077252/99902723-309a3200-2cd5-11eb-8acd-2925821781cf.png)

**Comment by chemzqm** [comment]
There's option of neovim-qt to disable gui pum
