### ISSUE TITLE
Option to disable color highlight

### ISSUE THREAD

**Issue by jlesquembre** [neoclide/coc-css#3]
For example, in this css:
```css
color: red;
```
The color background for the word `red` is red. I'd like to disable the color highlight. I tried to set
```json
  "coc.preferences.colorSupport": false,
```
on my `coc-settings.json` but if I go to insert mode and back to normal mode, the colors are highlighted again

**Comment by chemzqm** [comment]
Fixed on master of coc.nvim.

**Comment by jlesquembre** [comment]
I can confirm that now works. :)

Thanks for your amazing job on coc.nvim

**Comment by mawkler** [comment]
Can I disable the highlighting provided only by coc-css? `"coc.preferences.colorSupport": false` disables it for all extensions.

I tried fiddling with `css.colorDecorators.enable`, etc. but they didn't change anything.

**Comment by Frederick888** [comment]
@Melkster Changing https://github.com/neoclide/coc-css/blob/466552dbba8bf5de530da2e65b03b436b2be0dc5/server/cssServer.ts#L104 to `false` (or removing it), or commenting out https://github.com/neoclide/coc-css/blob/466552dbba8bf5de530da2e65b03b436b2be0dc5/server/cssServer.ts#L307-L312 works, but I'm not sure how to guard this behaviour behind a configuration.

I tried adding

```ts
const config = workspace.getConfiguration().get<any>('css', {}) as any
```

into this file but it just caused the server to crash.
