### ISSUE TITLE
<Plug>(coc-definition) in @<variables>

### ISSUE THREAD

**Issue by megagon** [neoclide/coc-css#30]
is it possible to go to the definition of variables in less files?
let's say I have @import "fonts" with @Black = something

and I have in my less background= @Black

is it possible to the definition with of @Black with <Plug>(coc-definition) ?

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by megagon** [comment]
@chemzqm 
thanks for the link, I found that I needed to set `let g:coc_filetype_map = {
		\ 'less': 'css', 
		\	}
`
but it seems like coc-css treats it as css, not less.
do you have any ideas about what can cause this?
<img width="601" alt="image" src="https://user-images.githubusercontent.com/4102581/107861961-6e34d400-6e5a-11eb-8c62-694b4a2f2e73.png">

thank you!


update: without this less: css mappings type is correct:

> [Trace - 00:41:37] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "file:///Users/apimenov/WebstormProjects/kltip/js/krs/js/Accounts/Accounts.less",
        "languageId": "less",
        "version": 1,
        "text": "@import \"../../../common/css/constants\";\n@import \"../../../common/css/positioning\";\n@import \"../../../common/css/links\";\n@import \"../../../common/css/buttons\";\n@import \"../../../common/css/fonts\";\n.TitleText {    \n  font-size: 18px;\n  color: @Black;\n  white-space: nowrap;\n}\n\n.AccountsList {\n  margin-top: 40px;\n\n  & > :not(:first-child) {\n    margin-top: 20px;\n  }\n\n  & > .TitleBlock {\n    display: flex;\n    align-items: center;\n\n    & > :not(:last-child) {\n      margin-right: 40px;\n    }\n\n    & .TitleText {\n      font-size: 28px;\n      color: @Black;\n      white-space: nowrap;\n    }\n  }\n\n  & .Quantity {\n    margin-left: 5px;\n    font-size: 22px;\n    color: @GrayWarm;\n  }\n\n  & .ModelLongColumn {\n    flex-basis: 200px;\n  }\n\n  & .ModelShortColumn {\n    flex-basis: 90px;\n  }\n\n  & .UserStatusColumn {\n    min-width: 70px;\n    justify-content: center;\n  }\n}\n\n.AddAccount {\n  & > .Wrapper {\n    padding: 24px @GlobalPadding;\n\n    & > :not(:last-child) {\n      margin-bottom: 20px;\n    }\n  }\n}\n\n.UserAccount {\n  & > .Wrapper {\n    padding: 24px @GlobalPadding;\n\n    & > :not(:last-child) {\n      margin-bottom: 20px;\n    }\n\n    & > .UserStatus {\n      display: flex;\n      font-size: 14px;\n      line-height: 16px;\n\n      & > :not(:last-child) {\n        margin-right: 8px;\n      }\n\n      & > .Dash {\n        color: @GrayWarm;\n      }\n    }\n\n    & > .Loading {\n      margin-left: auto;\n      margin-right: auto;\n    }\n\n    & > .InfoTable {\n      border-collapse: collapse;\n\n      & td {\n        min-height: 17px;\n        padding: 6px 12px 6px 0;\n        font-size: 14px;\n\n        & > .KeyText {\n          color: @GrayPlain;\n        }\n\n        & > .ValueText {\n          color: @Black;\n        }\n      }\n    }\n\n    & > .ButtonsBlock {\n      display: flex;\n\n      & > :not(:last-child) {\n        margin-right: 8px;\n      }\n\n      & > .Button {\n        display: flex;\n        min-width: 80px;\n        box-sizing: border-box;\n        align-items: center;\n        justify-content: center;\n\n        &.DeleteButton {\n          color: @RedAlizarin;\n\n          &:hover:not(:disabled) {\n            border-color: @RedAlizarin;;\n          }\n        }\n      }\n    }\n  }\n}\n\n.EditUserAccount {\n  & > .Wrapper {\n    padding: 24px @GlobalPadding;\n\n    & > :not(:last-child) {\n      margin-bottom: 20px;\n    }\n\n    & .Loading {\n      margin-left: auto;\n      margin-right: auto;\n    }\n  }\n}\n\n.AddAccountButton {\n  padding-bottom: 6px;\n  text-align: center;\n  padding-top: 6px;\n  height: auto;\n}\n"
    }
}


and after go definition on variable

> [Trace - 00:44:40] Received response 'textDocument/definition - (2)' in 14ms.
No result returned.


update2: it's doesn't work in vscode. that's insane :)
