### ISSUE TITLE
Rename breaks if scss mixin has a hyphen in the name

### ISSUE THREAD

**Issue by mrjones2014** [neoclide/coc-css#31]
When trying to use `coc-rename` on a SCSS mixin, it gets confused and thinks hyphens are not part of the name.

Autocomplete _does_ work, if I type `@include nav-` it will suggest `@include nav-item-accessible-styles` and pre-fill the param placeholders and everything — works perfect. But when I try to `coc-rename` the mixin, I get the behavior shown in the screenshot.

I've tried setting `"coc.preferences.hyphenAsKeyword": true` and that didn't change anything.

Any ideas?

![image](https://user-images.githubusercontent.com/8648891/109320717-511ae080-781e-11eb-9c15-55560e34ace4.png)

**Comment by chemzqm** [comment]
Add `-` to your buffer's iskeyword option.

**Comment by mrjones2014** [comment]
@chemzqm adding the following line to my `vimrc` file does not fix the issue

`set iskeyword+=@-@,-`

Let me know if I'm doing something wrong here

**Comment by chemzqm** [comment]
Check it by `:echo &iskeyword`

**Comment by mrjones2014** [comment]
@chemzqm `:echo &iskeyword` outputs the correct/expected characters. Adding `-` as a keyword did not fix the issue. Please reopen this issue.

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by mrjones2014** [comment]
.... isn't _this_ the language server for CSS/SCSS?
