### ISSUE TITLE
[scss unknownAtRules] [W] Unknown at rule @use

### ISSUE THREAD

**Issue by florianldt** [neoclide/coc-css#32]
From `sass` doc, `@import` usage is discouraged in favor of `@use` https://sass-lang.com/documentation/at-rules/import.

However, `@use` doesn't seems to be recognized using `coc-css` on vim but works on VS Code.

<img width="475" alt="Screen Shot 2021-05-24 at 11 15 05 PM" src="https://user-images.githubusercontent.com/9365651/119408376-e1fe3c80-bce5-11eb-86f4-6f0b86d22555.png">

Any ideas?

**Comment by chemzqm** [comment]
Could be caused by old version of vscode-css-languageservice

**Comment by florianldt** [comment]
Indeed pretty simple running `:CocInstall coc-css` to update the extension did the trick. Perfect.
