### ISSUE TITLE
css.colorDecorators.enable not working

### ISSUE THREAD

**Issue by jiyometrik** [neoclide/coc-css#33]
Hi, I'm relatively new to `coc.nvim` and Neovim in general.
I'm currently wondering why the `colorDecorators` aren't working, although they are enabled. The default settings haven't been changed.

Screenshots:
![image](https://user-images.githubusercontent.com/79387351/129896243-d6508270-6ebd-477a-86a3-cd2793e719b2.png)
Info:
**nvim version**
![image](https://user-images.githubusercontent.com/79387351/129895303-3506a4fb-7780-4be6-b7ed-2c2e3b42b6e3.png)

**on updating:**
![image](https://user-images.githubusercontent.com/79387351/129895178-c00609d2-7faa-4550-abdc-e00c328f2fab.png)

**after a css file has been loaded:**
![image](https://user-images.githubusercontent.com/79387351/129895996-bc22512a-e993-4607-bc6b-d92960ea8714.png)

**Comment by chemzqm** [comment]
You may have set `coc.preferences.colorSupport` to false.

 Checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by jiyometrik** [comment]
I'm sorry, but this did not work. I have set `"coc.preferences.colorSupport"` to `true`, and I have also set `"css.trace.server"` to `"verbose"`. Is there any other way to solve this problem?

**Comment by chemzqm** [comment]
Paste verbose output from langauge server

**Comment by jiyometrik** [comment]
![image](https://user-images.githubusercontent.com/79387351/129900130-eca5c54b-7934-453c-9d33-c597a5a427b0.png)
Is this right?

**Comment by chemzqm** [comment]
NO https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by jiyometrik** [comment]
sorry, i still don't know how to track verbose output.
