### ISSUE TITLE
intellisense for sass `@use` imports

### ISSUE THREAD

**Issue by assawalhy** [neoclide/coc-css#34]
Everything is working as expected, I only added this to my `init.vim`:

```vim
autocmd FileType scss setl iskeyword+=@-@
```

But now, I don't get autocompletion for the imported variables and mixins by using [`@use`](https://sass-lang.com/documentation/at-rules/use) of sass in both `.scss` and `.sass` files.

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
