### ISSUE TITLE
Variables separated with a '-' not being picked up correctly 

### ISSUE THREAD

**Issue by theTechGoose** [neoclide/coc-css#39]
Variables separated by a '-' are cut off.
Here is an example:

random css file
![image](https://user-images.githubusercontent.com/55964540/157707281-5e329f2e-7d4e-4ddf-ab8e-013685ad27a7.png)

_vars.scss
![image](https://user-images.githubusercontent.com/55964540/157707204-1fa40b0f-d269-413b-92b7-625f3da18fb9.png)

**Comment by theTechGoose** [comment]
Never mind, the solution is related to my previous issue;

Can you consider adding the following to the readme so that newer people like myself are less confused?

To get variable intelligence working correctly:

autocmd FileType scss setl iskeyword+=@
autocmd FileType scss setl iskeyword+=$
autocmd FileType scss setl iskeyword+=-

autocmd FileType css setl iskeyword+=@
autocmd FileType css setl iskeyword+=$
autocmd FileType css setl iskeyword+=-

**Comment by theTechGoose** [comment]
Still a small issue of the split variables are still in the list. How do I fix?


![image](https://user-images.githubusercontent.com/55964540/157745282-ffe27588-0839-4d6b-b310-8c67e151a0a3.png)

These three are part of the other variables and the plugin for some reason treats them as two separate variables.

$base
$shadow
$primary

**Comment by chemzqm** [comment]
It's by design https://github.com/neoclide/coc.nvim/blob/master/src/sources/native/around.ts#L21, you can disable around source and create your own source.
