### ISSUE TITLE
The link path is wrong!!

### ISSUE THREAD

**Issue by Vanillma** [neoclide/coc-css#41]
Hello, this link opens a issue, instead of the coc-css main page!!!
https://github.com/neoclide/coc.nvim/wiki/Language-servers#csslesssass

**Comment by chemzqm** [comment]
Fixed, you can edit the wiki as well.

**Comment by Vanillma** [comment]
> Fixed, you can edit the wiki as well.

Thank you...I didn't know!!...I've been using Github for a while now!...I'll definitely edit it myself next time :)
