### ISSUE TITLE
With neovim trying to install plugin prompts for github credentials?

### ISSUE THREAD

**Issue by mseidl** [neoclide/coc-css#5]
Is this right?  This doesn't seem like correct behavior.

**Comment by mseidl** [comment]
This happens with several of your plugins...

**Comment by chemzqm** [comment]
It's problem of your git configuration, I don't have this issue.

**Comment by mseidl** [comment]
I didn't have this with coc or any other github plugin.

**Comment by chemzqm** [comment]
This plugin doesn't use git at all.

**Comment by chemzqm** [comment]
Please provide detail information.
