### ISSUE TITLE
Clash with coc-tailwind in scss files

### ISSUE THREAD

**Issue by zurp** [neoclide/coc-css#7]
When using coc-css and coc-tailwind while editing a `scss` file, coc-css reports some errors.
This does not occur in `css` files.
coc-tailwind completion works as usual in `scss` files.

Thanks for the great work!

Edit:
Related question on VSCode: https://stackoverflow.com/questions/47607602/how-to-add-a-tailwind-css-rule-to-css-checker
There is a `css.lint.unknownAtRules` option, but it's missing for `scss`.

Edit 2:
Setting `scss.validate` to `false` hides the errors, but completion stops working.

![coc-css error](https://i.imgur.com/KVRwMr6.png)

**Comment by chemzqm** [comment]
It's problem of css language server, can't help.

**Comment by chemzqm** [comment]
Use `"scss.validate": false` to disable validate of scss files.
