### ISSUE TITLE
The completion of variables not working well.

### ISSUE THREAD

**Issue by thepenguinthatwants** [neoclide/coc-css#9]
I tried writing

$color-white: #fff;

and then $col it only suggest $color instead of the whole variable $color-white. 

The filetype I have is .scss

Any way to make it work better?

**Comment by chemzqm** [comment]
Add `-` to iskeyword option for scss files.

**Comment by thepenguinthatwants** [comment]
How do I add it as iskeyword option to scss?

**Comment by chemzqm** [comment]
Read help of vim.
